version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestonemoreProject
  gitServerName: prv_testabc_git
  gitUrl: https://github.com/priyabhat13d
  gitUsername: priyabhat13d
  gitBranch: main
